language: android
jdk:
  - oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-28.0.3
    - extra-google-google_play_services
  licenses:
    - '.+'
before_script:
    - mkdir libs
    - wget -O libs/libwebrtc-m87.aar https://gultsch.de/files/libwebrtc-m87.aar
script:
    - ./gradlew assembleConversationsFreeSystemRelease

before_install:
    - yes | sdkmanager "platforms;android-28"

before_deploy:
    - export TRAVIS_TAG=develop

deploy:
  skip_cleanup: true
  provider: releases
  file_glob: true
  file:
    - "build/outputs/apk/conversationsFreeSystem/release/*"
